MERGE INTO offers (
    code,
    title,
    description,
    offer_type,
    discount_value,
    max_discount,
    min_order_amount,
    valid_from,
    valid_till,
    total_usage_limit,
    per_user_usage_limit,
    active,
    applicable_movie_id,
    applicable_theater_id,
    payment_partner,
    assigned_user_id,
    offer_origin,
    source_app,
    source_offer_code,
    created_at,
    updated_at
) KEY(code) VALUES (
    'WELCOME20',
    'Welcome Offer',
    '20% off on first booking',
    'PERCENTAGE',
    20.00,
    200.00,
    100.00,
    DATEADD('DAY', -1, CURRENT_TIMESTAMP),
    DATEADD('DAY', 30, CURRENT_TIMESTAMP),
    5000,
    1,
    TRUE,
    NULL,
    NULL,
    NULL,
    NULL,
    'INTERNAL',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

MERGE INTO offers (
    code,
    title,
    description,
    offer_type,
    discount_value,
    max_discount,
    min_order_amount,
    valid_from,
    valid_till,
    total_usage_limit,
    per_user_usage_limit,
    active,
    applicable_movie_id,
    applicable_theater_id,
    payment_partner,
    assigned_user_id,
    offer_origin,
    source_app,
    source_offer_code,
    created_at,
    updated_at
) KEY(code) VALUES (
    'WEEKEND150',
    'Weekend Flat Discount',
    'Flat 150 off for weekend shows',
    'FLAT',
    150.00,
    NULL,
    300.00,
    DATEADD('DAY', -1, CURRENT_TIMESTAMP),
    DATEADD('DAY', 10, CURRENT_TIMESTAMP),
    2000,
    2,
    TRUE,
    NULL,
    NULL,
    NULL,
    NULL,
    'INTERNAL',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

MERGE INTO offers (
    code,
    title,
    description,
    offer_type,
    discount_value,
    max_discount,
    min_order_amount,
    valid_from,
    valid_till,
    total_usage_limit,
    per_user_usage_limit,
    active,
    applicable_movie_id,
    applicable_theater_id,
    payment_partner,
    assigned_user_id,
    offer_origin,
    source_app,
    source_offer_code,
    created_at,
    updated_at
) KEY(code) VALUES (
    'VIP50',
    'VIP User Offer',
    'User specific VIP discount',
    'PERCENTAGE',
    50.00,
    300.00,
    200.00,
    DATEADD('DAY', -1, CURRENT_TIMESTAMP),
    DATEADD('DAY', 15, CURRENT_TIMESTAMP),
    1000,
    3,
    TRUE,
    NULL,
    NULL,
    NULL,
    'user-999',
    'INTERNAL',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

MERGE INTO offers (
    code,
    title,
    description,
    offer_type,
    discount_value,
    max_discount,
    min_order_amount,
    valid_from,
    valid_till,
    total_usage_limit,
    per_user_usage_limit,
    active,
    applicable_movie_id,
    applicable_theater_id,
    payment_partner,
    assigned_user_id,
    offer_origin,
    source_app,
    source_offer_code,
    created_at,
    updated_at
) KEY(code) VALUES (
    'INT_PAYTM_PARTNER',
    'Paytm Partner Offer',
    'Partner campaign via Paytm app',
    'PERCENTAGE',
    25.00,
    250.00,
    150.00,
    DATEADD('DAY', -1, CURRENT_TIMESTAMP),
    DATEADD('DAY', 20, CURRENT_TIMESTAMP),
    3000,
    2,
    TRUE,
    NULL,
    NULL,
    NULL,
    NULL,
    'THIRD_PARTY',
    'PAYTM',
    'PAYTM25',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
